/**
 * Global “绘画” page mounted from the left sidebar. Not bound to any DSH
 * workspace or session: projects here are the gallery's own grouping.
 */
import { useCallback, useEffect, useLayoutEffect, useRef, useState, type KeyboardEvent as ReactKeyboardEvent } from 'react'
import { Bookmark, Images, Palette, Pencil, Settings, Trash2 } from 'lucide-react'
import { DEFAULT_PROJECT_ID, type FavoritePrompt, type GalleryItem } from '../gallery-types.js'
import type { SettingsView } from '../shared.js'
import { api, type ProjectSummary } from './api.js'
import { GalleryView } from './gallery-view.js'
import { useT, type LocaleService, type Translate } from './i18n.js'
import { PaintView } from './paint-view.js'
import { onGalleryChanged, usePaintSession } from './paint-session.js'
import { ALL_PROJECTS, FAVORITES, ProjectList } from './projects.js'
import { SettingsPanel } from './settings-view.js'
import { useToast } from './widgets.js'

type Tab = 'paint' | 'gallery' | 'prompts' | 'settings'
const STATE_KEY = 'copylee-image-gen.page.v1'
const POLL_MS = 4000

function loadState(): { tab?: Tab; project?: string; galleryFilter?: string } {
  try {
    return JSON.parse(localStorage.getItem(STATE_KEY) ?? '{}') as { tab?: Tab; project?: string; galleryFilter?: string }
  } catch {
    return {}
  }
}

export interface PaintingsPageProps {
  locale?: LocaleService | undefined
}

export function PaintingsPage({ locale }: PaintingsPageProps) {
  const t = useT(locale)
  const [initial] = useState(loadState)
  const [tab, setTab] = useState<Tab>(initial.tab ?? 'paint')
  const [settings, setSettings] = useState<SettingsView | null>(null)
  const [projects, setProjects] = useState<ProjectSummary[]>([])
  const [projectId, setProjectId] = useState(initial.project ?? DEFAULT_PROJECT_ID)
  const [galleryFilter, setGalleryFilter] = useState(initial.galleryFilter ?? ALL_PROJECTS)
  const [history, setHistory] = useState<GalleryItem[]>([])
  const [favoritesCount, setFavoritesCount] = useState(0)
  const [refreshKey, setRefreshKey] = useState(0)
  const [revision, setRevision] = useState<number | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [injected, setInjected] = useState<{ text?: string; reference?: GalleryItem['attachment']; nonce: number } | null>(null)
  const [toastNode, toast] = useToast()

  useEffect(() => {
    try {
      localStorage.setItem(STATE_KEY, JSON.stringify({ tab: tab === 'settings' ? 'paint' : tab, project: projectId, galleryFilter }))
    } catch {
      // storage unavailable: the page just reopens on its defaults
    }
  }, [tab, projectId, galleryFilter])

  const loadSettings = useCallback(() => {
    api.settings().then(setSettings, (failure: unknown) => setError(failure instanceof Error ? failure.message : String(failure)))
  }, [])
  useEffect(loadSettings, [loadSettings])

  const bump = useCallback(() => setRefreshKey(key => key + 1), [])
  const onError = useCallback((message: string) => setError(message), [])
  // Jobs finish even while this page is unmounted; refresh when one saves images.
  useEffect(() => onGalleryChanged(bump), [bump])
  const session = usePaintSession()

  // Projects, the paint tab's history strip and the favorites count.
  useEffect(() => {
    let cancelled = false
    void (async () => {
      try {
        const [projectList, page, favorites] = await Promise.all([
          api.gallery.projects(),
          api.gallery.list({ projectId, limit: 200 }),
          api.gallery.list({ favorite: true, limit: 1 }),
        ])
        if (cancelled) return
        setProjects(projectList.projects)
        setRevision(projectList.revision)
        setHistory(page.items)
        setFavoritesCount(favorites.total)
        if (!projectList.projects.some(project => project.id === projectId)) setProjectId(DEFAULT_PROJECT_ID)
      } catch (failure) {
        if (!cancelled) setError(failure instanceof Error ? failure.message : String(failure))
      }
    })()
    return () => { cancelled = true }
  }, [projectId, refreshKey])

  // Images generated by the Agent in any conversation show up without a reload.
  useEffect(() => {
    const timer = setInterval(() => {
      if (document.visibilityState !== 'visible') return
      api.gallery.revision().then(next => {
        if (revision !== null && next.revision !== revision) bump()
      }, () => {})
    }, POLL_MS)
    return () => clearInterval(timer)
  }, [revision, bump])

  const total = projects.reduce((sum, project) => sum + project.count, 0)
  const projectList = (gallery: boolean) => <ProjectList
    projects={projects}
    current={gallery ? galleryFilter : projectId}
    onSelect={id => gallery ? setGalleryFilter(id) : setProjectId(id)}
    onChanged={bump}
    t={t}
    onError={onError}
    {...(gallery ? { showAll: { total, favorites: favoritesCount } } : { busyIds: new Set(session.jobs.keys()) })}
  />

  const tabButton = (key: Tab, label: string, icon: JSX.Element) => <button type="button" role="tab" className="dig-tab" aria-selected={tab === key} onClick={() => setTab(key)}>{icon}{label}</button>

  return <div className="dig-root dig-page">
    <header className="dig-head">
      <h1>{t('panel')}</h1>
      <div className="dig-tabs" role="tablist">
        {tabButton('paint', t('tabPaint'), <Palette size={15} />)}
        {tabButton('gallery', t('tabGallery'), <Images size={15} />)}
        {tabButton('prompts', t('tabPrompts'), <Bookmark size={15} />)}
      </div>
      <span className="dig-spacer" />
      <button type="button" className="dig-icon-btn" aria-label={t('settingsTitle')} title={t('settingsTitle')} aria-pressed={false} onClick={() => setTab(tab === 'settings' ? 'paint' : 'settings')}><Settings size={17} /></button>
    </header>
    {error !== null && <div className="dig-error" role="alert" onClick={() => setError(null)} style={{ cursor: 'pointer' }}>{error}</div>}
    <div className="dig-body">
      {tab === 'paint' && <PaintView
        t={t}
        settings={settings}
        projectId={projectId}
        history={history}
        onGalleryChanged={bump}
        onError={onError}
        toast={toast}
        onOpenSettings={() => setTab('settings')}
        injected={injected}
        sideTop={projectList(false)}
        refreshKey={refreshKey}
      />}
      {tab === 'gallery' && <GalleryView
        t={t}
        settings={settings}
        projects={projects}
        filter={galleryFilter}
        refreshKey={refreshKey}
        onGalleryChanged={bump}
        onError={onError}
        toast={toast}
        onUseAsReference={item => { setInjected({ reference: item.attachment, nonce: Date.now() }); setTab('paint') }}
        onReusePrompt={item => { setInjected({ text: item.prompt, nonce: Date.now() }); setTab('paint') }}
        sideTop={projectList(true)}
      />}
      {tab === 'prompts' && <PromptsView t={t} refreshKey={refreshKey} onUse={text => { setInjected({ text, nonce: Date.now() }); setTab('paint') }} onError={onError} />}
      {tab === 'settings' && <div className="dig-scroll" style={{ flex: 1, minWidth: 0, padding: 16 }}>
        <SettingsPanel t={t} onSaved={setSettings} />
      </div>}
    </div>
    {toastNode}
  </div>
}

function PromptsView({ t, refreshKey, onUse, onError }: { t: Translate; refreshKey: number; onUse: (text: string) => void; onError: (message: string) => void }) {
  const [prompts, setPrompts] = useState<FavoritePrompt[]>([])
  const load = useCallback(() => {
    api.gallery.favoritePrompts().then(result => setPrompts(result.prompts), (failure: unknown) => onError(String(failure)))
  }, [onError])
  useEffect(load, [load, refreshKey])
  const [editing, setEditing] = useState<string | null>(null)
  const [draft, setDraft] = useState('')
  const cancelled = useRef(false)
  const startEdit = (prompt: FavoritePrompt): void => {
    cancelled.current = false
    setDraft(prompt.text)
    setEditing(prompt.id)
  }
  const commit = (id: string): void => {
    setEditing(null)
    if (cancelled.current) {
      cancelled.current = false
      return
    }
    const original = prompts.find(entry => entry.id === id)
    if (original === undefined || draft.trim() === original.text || draft.trim().length === 0) return
    api.gallery.updateFavoritePrompt(id, draft).then(load, (failure: unknown) => onError(failure instanceof Error ? failure.message : String(failure)))
  }
  return <div className="dig-scroll" style={{ flex: 1, minWidth: 0 }}>
    <div className="dig-prompts">
      {prompts.length === 0 && <div className="dig-empty"><Bookmark size={32} strokeWidth={1.4} />{t('noPrompts')}</div>}
      {prompts.map(prompt => <div key={prompt.id} className="dig-prompt-row">
        {editing === prompt.id
          ? <AutoTextarea
            className="dig-textarea dig-prompt-text dig-prompt-edit"
            value={draft}
            onChange={setDraft}
            onBlur={() => commit(prompt.id)}
            onKeyDown={event => {
              if (event.key === 'Escape') {
                cancelled.current = true
                setEditing(null)
              }
              if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) commit(prompt.id)
            }}
          />
          : <div className="dig-prompt-text" role="button" tabIndex={0} title={t('editPrompt')} style={{ cursor: 'text' }} onClick={() => startEdit(prompt)} onKeyDown={event => { if (event.key === 'Enter') startEdit(prompt) }}>{prompt.text}</div>}
        <button type="button" className="dig-icon-btn" title={t('editPrompt')} aria-label={t('editPrompt')} onClick={() => startEdit(prompt)}><Pencil size={15} /></button>
        <button type="button" className="dig-btn dig-btn-sm" onClick={() => onUse(prompt.text)}>{t('usePrompt')}</button>
        <button type="button" className="dig-icon-btn" aria-label={t('delete')} onClick={() => { void api.gallery.removeFavoritePrompt(prompt.id).then(load) }}><Trash2 size={15} /></button>
      </div>)}
    </div>
  </div>
}

/**
 * Textarea that opens at the height of its whole text and keeps growing
 * while typing (up to 70% of the viewport, then scrolls), with the caret
 * placed at the end.
 */
function AutoTextarea({ value, onChange, onBlur, onKeyDown, className }: {
  value: string
  onChange: (value: string) => void
  onBlur: () => void
  onKeyDown: (event: ReactKeyboardEvent<HTMLTextAreaElement>) => void
  className?: string
}) {
  const ref = useRef<HTMLTextAreaElement>(null)
  useLayoutEffect(() => {
    const area = ref.current
    if (area === null) return
    area.style.height = 'auto'
    area.style.height = `${String(Math.min(Math.max(area.scrollHeight + 2, 96), Math.round(window.innerHeight * 0.7)))}px`
  }, [value])
  useEffect(() => {
    const area = ref.current
    if (area === null) return
    area.focus()
    area.setSelectionRange(area.value.length, area.value.length)
  }, [])
  return <textarea ref={ref} className={className} value={value} onChange={event => onChange(event.target.value)} onBlur={onBlur} onKeyDown={onKeyDown} />
}
